# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'settings.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QTabWidget, QTextEdit, QToolButton,
    QWidget)
import resources_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(400, 500)
        Form.setMinimumSize(QSize(400, 500))
        Form.setMaximumSize(QSize(400, 500))
        self.back2homeBtn = QToolButton(Form)
        self.back2homeBtn.setObjectName(u"back2homeBtn")
        self.back2homeBtn.setGeometry(QRect(20, 20, 61, 41))
        self.back2homeBtn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.back2homeBtn.setStyleSheet(u"")
        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(30, 80, 351, 401))
        self.tabWidget.setStyleSheet(u"border:1px solid black;\n"
"border-radius:5px;")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.usernameLineEdit = QLineEdit(self.tab)
        self.usernameLineEdit.setObjectName(u"usernameLineEdit")
        self.usernameLineEdit.setGeometry(QRect(50, 40, 241, 31))
        self.usernameLineEdit.setStyleSheet(u"")
        self.passwordLineEdit = QLineEdit(self.tab)
        self.passwordLineEdit.setObjectName(u"passwordLineEdit")
        self.passwordLineEdit.setGeometry(QRect(50, 90, 241, 31))
        self.saveUserInfoBtn = QPushButton(self.tab)
        self.saveUserInfoBtn.setObjectName(u"saveUserInfoBtn")
        self.saveUserInfoBtn.setGeometry(QRect(50, 310, 241, 38))
        self.saveUserInfoBtn.setStyleSheet(u"")
        self.profileTextEdit = QTextEdit(self.tab)
        self.profileTextEdit.setObjectName(u"profileTextEdit")
        self.profileTextEdit.setGeometry(QRect(50, 140, 241, 151))
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.remoteUrlLineEdit = QLineEdit(self.tab_3)
        self.remoteUrlLineEdit.setObjectName(u"remoteUrlLineEdit")
        self.remoteUrlLineEdit.setGeometry(QRect(50, 30, 241, 31))
        self.remoteUrlLineEdit.setStyleSheet(u"")
        self.saveRemoteBtn = QPushButton(self.tab_3)
        self.saveRemoteBtn.setObjectName(u"saveRemoteBtn")
        self.saveRemoteBtn.setGeometry(QRect(50, 90, 241, 38))
        self.saveRemoteBtn.setStyleSheet(u"")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.providerLineEdit = QLineEdit(self.tab_2)
        self.providerLineEdit.setObjectName(u"providerLineEdit")
        self.providerLineEdit.setGeometry(QRect(120, 40, 201, 31))
        self.urlLineEdit = QLineEdit(self.tab_2)
        self.urlLineEdit.setObjectName(u"urlLineEdit")
        self.urlLineEdit.setGeometry(QRect(120, 120, 201, 31))
        self.modelLineEdit = QLineEdit(self.tab_2)
        self.modelLineEdit.setObjectName(u"modelLineEdit")
        self.modelLineEdit.setGeometry(QRect(120, 80, 201, 31))
        self.apikeyLineEdit = QLineEdit(self.tab_2)
        self.apikeyLineEdit.setObjectName(u"apikeyLineEdit")
        self.apikeyLineEdit.setGeometry(QRect(120, 160, 201, 31))
        self.label = QLabel(self.tab_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(50, 50, 53, 15))
        self.label.setStyleSheet(u"border:0px;")
        self.label_2 = QLabel(self.tab_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(50, 90, 53, 15))
        self.label_2.setStyleSheet(u"border:0px;")
        self.label_3 = QLabel(self.tab_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 130, 53, 15))
        self.label_3.setStyleSheet(u"border:0px;")
        self.label_4 = QLabel(self.tab_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(50, 170, 53, 15))
        self.label_4.setStyleSheet(u"border:0px;")
        self.saveModelBtn = QPushButton(self.tab_2)
        self.saveModelBtn.setObjectName(u"saveModelBtn")
        self.saveModelBtn.setGeometry(QRect(60, 320, 241, 31))
        self.saveModelBtn.setStyleSheet(u"")
        self.label_5 = QLabel(self.tab_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 210, 53, 15))
        self.label_5.setStyleSheet(u"border:0px;")
        self.genScorePromptTextEdit = QTextEdit(self.tab_2)
        self.genScorePromptTextEdit.setObjectName(u"genScorePromptTextEdit")
        self.genScorePromptTextEdit.setGeometry(QRect(120, 200, 201, 111))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.buttonColorBtn = QToolButton(self.tab_4)
        self.buttonColorBtn.setObjectName(u"buttonColorBtn")
        self.buttonColorBtn.setGeometry(QRect(50, 40, 241, 31))
        self.buttonColorBtn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.buttonColorBtn.setStyleSheet(u"")
        self.buttonHoverColorBtn = QToolButton(self.tab_4)
        self.buttonHoverColorBtn.setObjectName(u"buttonHoverColorBtn")
        self.buttonHoverColorBtn.setGeometry(QRect(50, 90, 241, 31))
        self.buttonHoverColorBtn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.buttonHoverColorBtn.setStyleSheet(u"")
        self.backgroundColorBtn = QToolButton(self.tab_4)
        self.backgroundColorBtn.setObjectName(u"backgroundColorBtn")
        self.backgroundColorBtn.setGeometry(QRect(50, 140, 241, 31))
        self.backgroundColorBtn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.backgroundColorBtn.setStyleSheet(u"")
        self.fontColorBtn = QToolButton(self.tab_4)
        self.fontColorBtn.setObjectName(u"fontColorBtn")
        self.fontColorBtn.setGeometry(QRect(50, 190, 241, 31))
        self.fontColorBtn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.fontColorBtn.setStyleSheet(u"")
        self.tabWidget.addTab(self.tab_4, "")
        self.logoutBtn = QToolButton(Form)
        self.logoutBtn.setObjectName(u"logoutBtn")
        self.logoutBtn.setGeometry(QRect(310, 20, 61, 41))
        self.logoutBtn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.logoutBtn.setStyleSheet(u"")

        self.retranslateUi(Form)

        self.tabWidget.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.back2homeBtn.setText(QCoreApplication.translate("Form", u"<-back", None))
        self.usernameLineEdit.setText(QCoreApplication.translate("Form", u"admin", None))
        self.usernameLineEdit.setPlaceholderText(QCoreApplication.translate("Form", u"\u7528\u6237\u540d", None))
        self.passwordLineEdit.setText(QCoreApplication.translate("Form", u"admin123", None))
        self.passwordLineEdit.setPlaceholderText(QCoreApplication.translate("Form", u"\u5bc6\u7801", None))
        self.saveUserInfoBtn.setText(QCoreApplication.translate("Form", u"\u4fdd\u5b58", None))
        self.profileTextEdit.setPlaceholderText(QCoreApplication.translate("Form", u"\u7528\u6237\u753b\u50cf\uff0c\u4ecb\u7ecd\u4e00\u4e0b\u4f60\u81ea\u5df1\uff0c\u8d8a\u6e05\u6670\u8be6\u7ec6\u8d8a\u597d\uff0c\u5c06\u4f1a\u63d0\u4f9b\u7ed9\u5927\u6a21\u578b\u8fdb\u884c\u53c2\u8003\uff0c\u7ed9\u51fa\u4e2a\u6027\u5316\u5206\u6570", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Form", u"\u6211\u7684", None))
        self.remoteUrlLineEdit.setText("")
        self.remoteUrlLineEdit.setPlaceholderText(QCoreApplication.translate("Form", u"\u8fdc\u7a0b\u94fe\u63a5", None))
        self.saveRemoteBtn.setText(QCoreApplication.translate("Form", u"\u4fdd\u5b58", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Form", u"\u8fdc\u7a0b\u8bbe\u7f6e", None))
        self.providerLineEdit.setText(QCoreApplication.translate("Form", u"openai", None))
        self.providerLineEdit.setPlaceholderText(QCoreApplication.translate("Form", u"\u7aef\u70b9", None))
        self.urlLineEdit.setText(QCoreApplication.translate("Form", u"https://api.openai.com/v1", None))
        self.urlLineEdit.setPlaceholderText(QCoreApplication.translate("Form", u"\u7aef\u70b9", None))
        self.modelLineEdit.setText(QCoreApplication.translate("Form", u"deepseek-chat", None))
        self.modelLineEdit.setPlaceholderText(QCoreApplication.translate("Form", u"\u7aef\u70b9", None))
        self.apikeyLineEdit.setText(QCoreApplication.translate("Form", u"sk-a6ae756840b146e4aab7020c0865041d", None))
        self.apikeyLineEdit.setPlaceholderText(QCoreApplication.translate("Form", u"\u7aef\u70b9", None))
        self.label.setText(QCoreApplication.translate("Form", u"\u7aef\u70b9\uff1a", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"\u6a21\u578b\uff1a", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"url\uff1a", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"\u5bc6\u94a5\uff1a", None))
        self.saveModelBtn.setText(QCoreApplication.translate("Form", u"\u4fdd\u5b58", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"prompt\uff1a", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Form", u"\u6a21\u578b\u8bbe\u7f6e", None))
        self.buttonColorBtn.setText(QCoreApplication.translate("Form", u"\u6309\u94ae\u989c\u8272", None))
        self.buttonHoverColorBtn.setText(QCoreApplication.translate("Form", u"\u6309\u94ae\u60ac\u6d6e\u989c\u8272", None))
        self.backgroundColorBtn.setText(QCoreApplication.translate("Form", u"\u80cc\u666f\u989c\u8272", None))
        self.fontColorBtn.setText(QCoreApplication.translate("Form", u"\u5b57\u4f53\u989c\u8272", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("Form", u"\u4e3b\u9898", None))
        self.logoutBtn.setText(QCoreApplication.translate("Form", u"logout", None))
    # retranslateUi

